"""Embedded wordlists and regex patterns for bug-bounty recon.

Everything lives in-memory so there are no external file dependencies.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Sensitive path wordlist (~200 entries, bug-bounty-focused)
# ---------------------------------------------------------------------------
BB_PATHS: list[str] = [
    # Version control / CI
    "/.git/HEAD",
    "/.git/config",
    "/.gitignore",
    "/.svn/entries",
    "/.hg/hgrc",
    "/.bzr/branch-format",
    "/.github/workflows",
    # Environment / config
    "/.env",
    "/.env.local",
    "/.env.production",
    "/.env.staging",
    "/.env.backup",
    "/.env.old",
    "/.env.bak",
    "/.env.dev",
    "/config.php",
    "/config.yml",
    "/config.yaml",
    "/config.json",
    "/config.xml",
    "/config.inc.php",
    "/configuration.php",
    "/settings.py",
    "/settings.json",
    "/local_settings.py",
    "/application.yml",
    "/application.properties",
    "/appsettings.json",
    "/web.config",
    # WordPress
    "/wp-config.php",
    "/wp-config.php.bak",
    "/wp-config.php.old",
    "/wp-config.php.save",
    "/wp-login.php",
    "/wp-admin/",
    "/wp-json/wp/v2/users",
    "/xmlrpc.php",
    "/wp-includes/",
    "/wp-content/debug.log",
    # Admin panels
    "/admin",
    "/admin/",
    "/admin/login",
    "/administrator/",
    "/admin.php",
    "/cpanel",
    "/dashboard",
    "/manage",
    "/management",
    "/portal",
    "/panel",
    "/webadmin",
    "/siteadmin",
    "/controlpanel",
    "/_admin",
    "/admin-console",
    # API / docs
    "/api",
    "/api/v1",
    "/api/v2",
    "/api/v3",
    "/api/docs",
    "/api/swagger",
    "/api/graphql",
    "/graphql",
    "/graphiql",
    "/swagger-ui.html",
    "/swagger.json",
    "/swagger.yaml",
    "/openapi.json",
    "/api-docs",
    "/redoc",
    "/v1/",
    "/v2/",
    "/docs",
    "/_api",
    "/rest/",
    # Debugging / info
    "/phpinfo.php",
    "/info.php",
    "/server-status",
    "/server-info",
    "/.DS_Store",
    "/Thumbs.db",
    "/debug",
    "/debug/default/view",
    "/debug/pprof/",
    "/trace",
    "/metrics",
    "/health",
    "/healthcheck",
    "/status",
    "/actuator",
    "/actuator/env",
    "/actuator/health",
    "/actuator/info",
    "/actuator/beans",
    "/actuator/configprops",
    "/actuator/mappings",
    "/actuator/heapdump",
    "/elmah.axd",
    # Backups / archives
    "/backup.zip",
    "/backup.tar.gz",
    "/backup.sql",
    "/db.sql",
    "/database.sql",
    "/dump.sql",
    "/site.zip",
    "/www.zip",
    "/backup/",
    "/old/",
    "/temp/",
    "/tmp/",
    "/bak/",
    "/save/",
    # Dependency / build
    "/composer.json",
    "/composer.lock",
    "/package.json",
    "/package-lock.json",
    "/yarn.lock",
    "/Gemfile",
    "/Gemfile.lock",
    "/Pipfile",
    "/Pipfile.lock",
    "/requirements.txt",
    "/Dockerfile",
    "/docker-compose.yml",
    "/Makefile",
    "/Gruntfile.js",
    "/Gulpfile.js",
    "/webpack.config.js",
    "/tsconfig.json",
    # Apache / Nginx
    "/.htaccess",
    "/.htpasswd",
    "/nginx.conf",
    "/server-status",
    # Security / policy
    "/.well-known/security.txt",
    "/security.txt",
    "/robots.txt",
    "/sitemap.xml",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    "/humans.txt",
    # Cloud metadata (only useful in certain contexts)
    "/latest/meta-data/",
    # Common CMS
    "/joomla/",
    "/drupal/",
    "/magento/",
    "/cms/",
    # Login / auth
    "/login",
    "/signin",
    "/signup",
    "/register",
    "/logout",
    "/forgot-password",
    "/reset-password",
    "/auth",
    "/oauth",
    "/sso",
    "/saml",
    "/.well-known/openid-configuration",
    # File upload / media
    "/upload",
    "/uploads/",
    "/media/",
    "/files/",
    "/static/",
    "/assets/",
    "/images/",
    "/img/",
    # Error / test pages
    "/error",
    "/404",
    "/500",
    "/test",
    "/test.php",
    "/test.html",
    "/example",
    "/sample",
    "/demo",
    # Logs
    "/logs/",
    "/log/",
    "/error.log",
    "/access.log",
    "/debug.log",
    # Source maps
    "/main.js.map",
    "/app.js.map",
    "/bundle.js.map",
    "/vendor.js.map",
    # Internal tools
    "/phpmyadmin/",
    "/pma/",
    "/adminer.php",
    "/mailhog",
    "/kibana",
    "/grafana",
    "/prometheus",
    "/jenkins",
    "/sonar",
    "/nexus",
    "/console",
    "/shell",
]

# ---------------------------------------------------------------------------
# JS secret regex patterns — compiled for speed
# ---------------------------------------------------------------------------
_SECRET_PATTERNS_RAW: dict[str, str] = {
    "AWS Access Key": r"AKIA[0-9A-Z]{16}",
    "AWS Secret Key": r"(?i)aws[_\-]?secret[_\-]?access[_\-]?key\s*[:=]\s*['\"]?([A-Za-z0-9/+=]{40})['\"]?",
    "Google API Key": r"AIza[0-9A-Za-z\-_]{35}",
    "Google OAuth Token": r"ya29\.[0-9A-Za-z\-_]+",
    "GitHub Token": r"gh[pousr]_[A-Za-z0-9_]{36,255}",
    "GitHub Classic Token": r"ghp_[A-Za-z0-9]{36}",
    "Slack Token": r"xox[baprs]-[0-9A-Za-z\-]{10,250}",
    "Slack Webhook": r"https://hooks\.slack\.com/services/T[A-Za-z0-9]+/B[A-Za-z0-9]+/[A-Za-z0-9]+",
    "Stripe Secret Key": r"sk_live_[0-9a-zA-Z]{24,}",
    "Stripe Publishable Key": r"pk_live_[0-9a-zA-Z]{24,}",
    "Stripe Test Key": r"sk_test_[0-9a-zA-Z]{24,}",
    "Square Access Token": r"sq0atp-[0-9A-Za-z\-_]{22,}",
    "Square OAuth Secret": r"sq0csp-[0-9A-Za-z\-_]{43,}",
    "Twilio API Key": r"SK[0-9a-fA-F]{32}",
    "Twilio Account SID": r"AC[0-9a-fA-F]{32}",
    "SendGrid API Key": r"SG\.[A-Za-z0-9\-_]{22,}\.[A-Za-z0-9\-_]{43,}",
    "Mailgun API Key": r"key-[0-9a-zA-Z]{32}",
    "Firebase Key": r"AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}",
    "Heroku API Key": r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
    "JWT Token": r"eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]+",
    "Bearer Token (Generic)": r"(?i)bearer\s+[A-Za-z0-9\-_\.~\+/]+=*",
    "Authorization Header": r'(?i)(?:authorization|auth[_\-]?token|api[_\-]?key|api[_\-]?secret|access[_\-]?token|secret[_\-]?key)\s*[:=]\s*["\']([A-Za-z0-9\-_\.~\+/]{8,})["\']',
    "Private Key Block": r"-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----",
    "Password in URL": r"(?i)(?:password|passwd|pwd)\s*[:=]\s*['\"]?[^\s'\"]{4,}['\"]?",
    "Database URL": r"(?i)(?:mysql|postgres|postgresql|mongodb|redis|amqp)://[^\s'\"]+",
    "Azure Storage Key": r"(?i)DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{86,}",
    "Telegram Bot Token": r"[0-9]{8,10}:[A-Za-z0-9_-]{35}",
    "Discord Bot Token": r"[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9\-_]{6}\.[A-Za-z0-9\-_]{27,}",
    "PayPal Braintree Token": r"access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}",
    "Shopify Token": r"shpat_[a-fA-F0-9]{32}",
    "Shopify Shared Secret": r"shpss_[a-fA-F0-9]{32}",
    "NPM Token": r"npm_[A-Za-z0-9]{36}",
}

SECRET_PATTERNS: dict[str, re.Pattern] = {
    name: re.compile(pattern) for name, pattern in _SECRET_PATTERNS_RAW.items()
}

# ---------------------------------------------------------------------------
# Open redirect parameter names (most commonly abused)
# ---------------------------------------------------------------------------
REDIRECT_PARAMS: list[str] = [
    "url",
    "redirect",
    "redirect_url",
    "redirect_uri",
    "return",
    "return_url",
    "returnUrl",
    "returnTo",
    "return_to",
    "next",
    "next_url",
    "redir",
    "rurl",
    "dest",
    "destination",
    "go",
    "goto",
    "target",
    "to",
    "link",
    "out",
    "view",
    "ref",
    "continue",
    "continue_url",
    "callback",
    "callback_url",
    "fallback",
    "checkout_url",
    "login_url",
    "logout_url",
    "image_url",
    "success_url",
    "fail_url",
    "forward",
]

# Open redirect test payloads (non-destructive)
REDIRECT_PAYLOADS: list[str] = [
    "https://evil.com",
    "//evil.com",
    "/\\evil.com",
    "https://evil.com@legitimate.com",
    "https:evil.com",
    "////evil.com",
]

# ---------------------------------------------------------------------------
# Common S3 / cloud bucket name patterns
# ---------------------------------------------------------------------------
BUCKET_SUFFIXES: list[str] = [
    "",
    "-assets",
    "-backup",
    "-backups",
    "-bak",
    "-cdn",
    "-content",
    "-data",
    "-dev",
    "-development",
    "-files",
    "-images",
    "-img",
    "-logs",
    "-media",
    "-private",
    "-prod",
    "-production",
    "-public",
    "-staging",
    "-static",
    "-storage",
    "-test",
    "-testing",
    "-uploads",
    "-web",
    ".assets",
    ".backup",
    ".cdn",
    ".dev",
    ".media",
    ".prod",
    ".static",
    ".uploads",
]

# ---------------------------------------------------------------------------
# Info harvester patterns
# ---------------------------------------------------------------------------
EMAIL_PATTERN = re.compile(
    r"\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Z|a-z]{2,7}\b"
)
PHONE_PATTERN = re.compile(
    r"(?:\+?\d{1,3}[\s\-]?)?\(?\d{2,4}\)?[\s\-]?\d{3,4}[\s\-]?\d{3,4}"
)
INTERNAL_PATH_PATTERN = re.compile(
    r"(?:/(?:home|var|usr|opt|etc|tmp|root|srv|mnt)/[A-Za-z0-9._/\-]+)"
)
